### ISSUE TITLE
error joining server

### ISSUE THREAD

**Issue by AXCWG** [dragon99z/DragonInvSync#1]
when joining, server crashes. 

log: 
[03:51:48] [Server thread/ERROR]: Couldn't place player in world
java.lang.NullPointerException: Cannot invoke "java.sql.Connection.createStatement()" because "de.dragon99z.dragoninvsync.Func.MySQL.con" is null
	at de.dragon99z.dragoninvsync.Func.Sync.getEChestHash(Sync.java:373) ~[DragonInvSync-0.1.1-SNAPSHOT.jar:?]
	at de.dragon99z.dragoninvsync.Func.Sync.syncAllToPlayer(Sync.java:467) ~[DragonInvSync-0.1.1-SNAPSHOT.jar:?]
	at de.dragon99z.dragoninvsync.Events.onPlayerJoinEvent.joinPlayerSync(onPlayerJoinEvent.java:41) ~[DragonInvSync-0.1.1-SNAPSHOT.jar:?]
	at de.dragon99z.dragoninvsync.Events.onPlayerJoinEvent.<init>(onPlayerJoinEvent.java:28) ~[DragonInvSync-0.1.1-SNAPSHOT.jar:?]
	at de.dragon99z.dragoninvsync.DragonInvSync.lambda$registerEvents$0(DragonInvSync.java:105) ~[DragonInvSync-0.1.1-SNAPSHOT.jar:?]
	at net.fabricmc.fabric.api.networking.v1.ServerPlayConnectionEvents.lambda$static$2(ServerPlayConnectionEvents.java:48) ~[fabric-networking-api-v1-4.2.0+ab7edbacd1-a8c169b2f3111a93.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.onClientReady(ServerPlayNetworkAddon.java:63) ~[fabric-networking-api-v1-4.2.0+ab7edbacd1-a8c169b2f3111a93.jar:?]
	at net.minecraft.class_3324.handler$ban001$fabric-networking-api-v1$handlePlayerConnection(class_3324.java:4506) ~[server-intermediary.jar:?]
	at net.minecraft.class_3324.method_14570(class_3324.java:203) ~[server-intermediary.jar:?]
	at net.minecraft.class_8610.mixinextras$bridge$method_14570$40(class_8610.java) ~[server-intermediary.jar:?]
	at net.minecraft.class_8610.wrapOperation$chm000$polymer-networking$polymerNet$prePlayHandshakeHackfest(class_8610.java:1038) ~[server-intermediary.jar:?]
	at net.minecraft.class_8610.method_52408(class_8610.java:152) ~[server-intermediary.jar:?]
	at net.minecraft.class_8736.method_53043(class_8736.java:22) ~[server-intermediary.jar:?]
	at net.minecraft.class_8736.method_11054(class_8736.java:8) ~[server-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:27) ~[server-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:162) ~[server-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:864) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:173) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:136) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:846) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:840) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:145) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18857(MinecraftServer.java:810) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:815) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:702) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[server-intermediary.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[03:51:48] [Netty Server Play IO #0/WARN]: Failed to load language resource at flan:lang/zh_cn.json
com.google.gson.JsonSyntaxException: Expected EDITCLAIM.desc to be a string, was an array (["给予...限"])
	at net.minecraft.class_3518.method_15287(class_3518.java:120) ~[server-intermediary.jar:?]
	at net.minecraft.class_2477.method_29425(class_2477.java:85) ~[server-intermediary.jar:?]
	at xyz.nucleoid.server.translations.impl.language.LanguageReader.read(LanguageReader.java:19) ~[server_translations_api-2.3.1+1.21-pre2-9e19fee7fd71eb90.jar:?]
	at xyz.nucleoid.server.translations.impl.language.LanguageReader.lambda$collectDataPackTranslations$1(LanguageReader.java:40) ~[server_translations_api-2.3.1+1.21-pre2-9e19fee7fd71eb90.jar:?]
	at xyz.nucleoid.server.translations.impl.language.TranslationStore.tryLoad(TranslationStore.java:50) ~[server_translations_api-2.3.1+1.21-pre2-9e19fee7fd71eb90.jar:?]
	at xyz.nucleoid.server.translations.impl.language.TranslationStore.get(TranslationStore.java:37) ~[server_translations_api-2.3.1+1.21-pre2-9e19fee7fd71eb90.jar:?]
	at xyz.nucleoid.server.translations.impl.ServerTranslations.createLanguage(ServerTranslations.java:124) ~[server_translations_api-2.3.1+1.21-pre2-9e19fee7fd71eb90.jar:?]
	at xyz.nucleoid.server.translations.impl.ServerTranslations.getLanguage(ServerTranslations.java:109) ~[server_translations_api-2.3.1+1.21-pre2-9e19fee7fd71eb90.jar:?]
	at xyz.nucleoid.server.translations.impl.ServerTranslations.getLanguage(ServerTranslations.java:93) ~[server_translations_api-2.3.1+1.21-pre2-9e19fee7fd71eb90.jar:?]
	at xyz.nucleoid.server.translations.api.LocalizationTarget.getLanguage(LocalizationTarget.java:28) ~[server_translations_api-2.3.1+1.21-pre2-9e19fee7fd71eb90.jar:?]
	at net.minecraft.class_2588.mdece7d2$server_translations_api$lambda$stapi$addTranslationFallback$1$0(class_2588.java:545) ~[server-intermediary.jar:?]
	at com.mojang.serialization.MapEncoder$1.encode(MapEncoder.java:26) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.MapCodec$2.encode(MapCodec.java:82) ~[datafixerupper-8.0.16.jar:?]
	at net.minecraft.class_8824$class_8825.encode(class_8824.java:156) ~[server-intermediary.jar:?]
	at net.minecraft.class_8824$class_8912.encode(class_8824.java:122) ~[server-intermediary.jar:?]
	at net.minecraft.class_5699$3.encode(class_5699.java:234) ~[server-intermediary.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$6.encode(RecordCodecBuilder.java:295) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder$2.encode(RecordCodecBuilder.java:112) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.MapCodec$MapCodecCodec.encode(MapCodec.java:163) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.codecs.EitherCodec.lambda$encode$4(EitherCodec.java:35) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.datafixers.util.Either$Right.map(Either.java:99) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.codecs.EitherCodec.encode(EitherCodec.java:33) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.codecs.EitherCodec.encode(EitherCodec.java:11) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.Encoder$1.encode(Encoder.java:25) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.Codec$2.encode(Codec.java:80) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.Codec$RecursiveCodec.encode(Codec.java:217) ~[datafixerupper-8.0.16.jar:?]
	at com.mojang.serialization.Encoder.encodeStart(Encoder.java:14) ~[datafixerupper-8.0.16.jar:?]
	at net.minecraft.class_9135.method_56369(class_9135.java:254) ~[server-intermediary.jar:?]
	at net.minecraft.class_9139$8.encode(class_9139.java:81) ~[server-intermediary.jar:?]
	at net.minecraft.class_9139$8.encode(class_9139.java:81) ~[server-intermediary.jar:?]
	at net.minecraft.class_9139$9.method_56442(class_9139.java:97) ~[server-intermediary.jar:?]
	at net.minecraft.class_9139$9.encode(class_9139.java:87) ~[server-intermediary.jar:?]
	at net.minecraft.class_9136.method_56426(class_9136.java:53) ~[server-intermediary.jar:?]
	at net.minecraft.class_9136.encode(class_9136.java:14) ~[server-intermediary.jar:?]
	at net.minecraft.class_2545.method_10838(class_2545.java:26) ~[server-intermediary.jar:?]
	at net.minecraft.class_2545.encode(class_2545.java:12) ~[server-intermediary.jar:?]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[netty-codec-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113) ~[netty-codec-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113) ~[netty-transport-4.1.97.Final.jar:?]
	at net.minecraft.class_2535$2.write(class_2535.java:530) ~[server-intermediary.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:966) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:934) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:984) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306) ~[netty-transport-4.1.97.Final.jar:?]
	at net.minecraft.class_2535.method_36942(class_2535.java:350) ~[server-intermediary.jar:?]
	at net.minecraft.class_2535.method_52917(class_2535.java:345) ~[server-intermediary.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.97.Final.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[03:51:48] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NullPointerException: Cannot invoke "java.sql.Connection.createStatement()" because "de.dragon99z.dragoninvsync.Func.MySQL.con" is null
	at de.dragon99z.dragoninvsync.Func.Sync.setEChestHash(Sync.java:354) ~[DragonInvSync-0.1.1-SNAPSHOT.jar:?]
	at de.dragon99z.dragoninvsync.Func.Sync.syncAllToDatabase(Sync.java:439) ~[DragonInvSync-0.1.1-SNAPSHOT.jar:?]
	at de.dragon99z.dragoninvsync.Events.onPlayerLeaveEvent.leftPlayerSync(onPlayerLeaveEvent.java:30) ~[DragonInvSync-0.1.1-SNAPSHOT.jar:?]
	at de.dragon99z.dragoninvsync.Events.onPlayerLeaveEvent.<init>(onPlayerLeaveEvent.java:21) ~[DragonInvSync-0.1.1-SNAPSHOT.jar:?]
	at de.dragon99z.dragoninvsync.DragonInvSync.lambda$registerEvents$1(DragonInvSync.java:107) ~[DragonInvSync-0.1.1-SNAPSHOT.jar:?]
	at net.fabricmc.fabric.api.networking.v1.ServerPlayConnectionEvents.lambda$static$4(ServerPlayConnectionEvents.java:59) ~[fabric-networking-api-v1-4.2.0+ab7edbacd1-a8c169b2f3111a93.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.invokeDisconnectEvent(ServerPlayNetworkAddon.java:124) ~[fabric-networking-api-v1-4.2.0+ab7edbacd1-a8c169b2f3111a93.jar:?]
	at net.fabricmc.fabric.impl.networking.AbstractNetworkAddon.handleDisconnect(AbstractNetworkAddon.java:160) ~[fabric-networking-api-v1-4.2.0+ab7edbacd1-a8c169b2f3111a93.jar:?]
	at net.minecraft.class_2535.handler$baf000$fabric-networking-api-v1$disconnectAddon(class_2535.java:819) ~[server-intermediary.jar:?]
	at net.minecraft.class_2535.method_10768(class_2535.java:673) ~[server-intermediary.jar:?]
	at net.minecraft.class_3242.method_14357(class_3242.java:189) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1032) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:299) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[server-intermediary.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]

conf: 
# Config File for InvSync

[general]
syncDelay = 5

# Settings that apply regardless of database used
[database]
name = "InvSync"
# Allowed Values: mysql
type = "mysql"

[mysql]
address = ".cn"
port = 3306
username = "external"
password = ""
debug = true

please, add some kind of error handling or something because the server crashes immediately when load. why not add some notifications in the text box or something liek taht

**Comment by cr-gomezm** [comment]
Exact same error here, no idea what really happened because the latest change made was updating fabric server to 0.16.2 and just after the update everything was working fine. 

Reverted back 48hrs with a Backup (last known working date) and problem persists.
MySQL is also working fine.

Servers work perfectly till a user tries to connect, which immediately trigger the fatal error and shutdown.
